### ISSUE TITLE
Spaces in commands

### ISSUE THREAD

**Issue by MassimoSporchia** [jenkinsci/azure-cli-plugin#7]
Hello,

I was trying to tag resources via the azureCLI plugin via the command:
`azureCLI commands: [[exportVariablesString: '', script: "az group update -n ${resource_group_name} --set tags.Company=Hello"]], principalCredentialId: 'jenkins-ci-azure-app'`

The issue occurs when I try to specify a spaced value, like the following:
`azureCLI commands: [[exportVariablesString: '', script: "az group update -n ${resource_group_name} --set tags.Company=\"Hello World\""]], principalCredentialId: 'jenkins-ci-azure-app'`

The resulting tag is:
"Company": "\"Hello"

When run from the native CLI via:
`az group update -n ${resource_group_name} --set tags.Company="Hello World"`

The resulting tag is:
"Company": "Hello World"

I'm sure it has do be done this way (see: https://github.com/Azure/azure-cli/issues/1863 )

**Comment by torosent** [comment]
Fixed with 0.9 version

**Comment by MassimoSporchia** [comment]
@torosent Thanks! I'll try it as soon as possible.
As far as you are aware, is there a way to specify, using azure CLI, tag names with spaces?
AFAIK the only way is to use powershell: 
`Set-AzureRmResourceGroup`

**Comment by torosent** [comment]
`--tags "test key=test value"` works for me
